services:
  backend:
    container_name: carbon-nexus-backend
    build: 
      context: .
      dockerfile: ./external/docker/backend.Dockerfile
    ports:
      - 8080:8080
    networks:
      - carbon-nexus-network
    
  frontend:
    container_name: carbon-nexus-frontend
    build: 
      context: .
      dockerfile: ./external/docker/frontend.Dockerfile
    ports:
      - 3000:3000
    networks:
      - carbon-nexus-network

networks:
  carbon-nexus-network:
    driver: bridge