services:
  backend:
    container_name: TSPlatform-backend
    build: 
      context: .
      dockerfile: ./external/docker/backend.Dockerfile
    ports:
      - 8080:8080
    networks:
      - TSPlatform-network
    
  frontend:
    container_name: TSPlatform-frontend
    build: 
      context: .
      dockerfile: ./external/docker/frontend.Dockerfile
    ports:
      - 3000:3000
    networks:
      - TSPlatform-network

networks:
  TSPlatform-network:
    driver: bridge