services:
  backend:
    container_name: TSPlatform-backend
    build: 
      context: .
      dockerfile: ./external/docker/backend.Dockerfile
    ports:
      - 8080:8080
    networks:
      - TSPlatform-network
    
  frontend:
    container_name: TSPlatform-frontend
    build: 
      context: .
      dockerfile: ./external/docker/frontend.Dockerfile
    ports:
      - 3000:3000
    networks:
      - TSPlatform-network

  nginx:
    container_name: TSPlatform-nginx
    build: 
      context: ./external/nginx
      dockerfile: ./Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
      - frontend
    networks:
      - TSPlatform-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  TSPlatform-network:
    driver: bridge