name: Pipeline

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

# for testing
env:
  FRONTEND_URL: http://localhost:3000
  DATABASE_URL: file:./testing.db

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.4
      
      - name: Install dependencies
        run: bun i

      - name: Lint code
        run: bun run lint
  
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.4
      
      - name: Install dependencies
        run: bun i

      - name: Setup database
        run: cd apps/backend && bun run prisma:migrate

      - name: Run unit tests
        run: cd apps/backend && bun run test -t Service
      
      - name: Run integration tests
        run: cd apps/backend && bun run test -t Controller

      # - name: Run frontend tests
      #   run: cd apps/frontend && bun run test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [test, static-analysis]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.4
      
      - name: Install dependencies
        run: bun i
      
      - name: Build
        run: bun run build
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: backend
          path: |
            apps/backend/dist
            apps/frontend/.next
      